name: Checks

on: push

jobs:
  test-list:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker-compose stack up
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Create users and give permissions
        run: |
          sudo adduser \
          --disabled-password \
          --no-create-home \
          django-user && \
          chown -R django-user:django-user /app && \
          chmod -R 755 /app && \
          mkdir -p /vol/web/media && \
          mkdir -p /vol/web/static && \
          chown -R django-user:django-user /vol && \
          chmod -R 755 /vol
      - name: Test
        run: sudo docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
