name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-list:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: docker-compose stack up
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check container permissions
        run: docker-compose run --rm app sh -c "ls -la"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
